"""Add cascade delete to models

Revision ID: 447764dfe794
Revises: 62fac3fe81c3
Create Date: 2025-02-23 10:46:02.612542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '447764dfe794'
down_revision: Union[str, None] = '62fac3fe81c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('leases_unit_id_fkey', 'leases', type_='foreignkey')
    op.drop_constraint('leases_tenant_id_fkey', 'leases', type_='foreignkey')
    op.create_foreign_key(None, 'leases', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'leases', 'units', ['unit_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('payments_lease_id_fkey', 'payments', type_='foreignkey')
    op.drop_constraint('payments_tenant_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'payments', 'leases', ['lease_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_tenant_id_fkey', 'payments', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key('payments_lease_id_fkey', 'payments', 'leases', ['lease_id'], ['id'])
    op.drop_constraint(None, 'leases', type_='foreignkey')
    op.drop_constraint(None, 'leases', type_='foreignkey')
    op.create_foreign_key('leases_tenant_id_fkey', 'leases', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key('leases_unit_id_fkey', 'leases', 'units', ['unit_id'], ['id'])
    # ### end Alembic commands ###
