"""Initial migration

Revision ID: 62fac3fe81c3
Revises: 937f2af4558c
Create Date: 2025-02-22 23:03:52.921006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62fac3fe81c3'
down_revision: Union[str, None] = '937f2af4558c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'description')
    # ### end Alembic commands ###
